[Unit]
Description=Make key mounts shared (required for Calico BPF + containerd)
DefaultDependencies=no
Before=containerd.service kubelet.service
After=systemd-remount-fs.service

[Service]
Type=oneshot
ExecStart=/bin/mount --make-rshared /
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target